const fmt=v=>new Intl.NumberFormat('vi-VN').format(v*1000)+'đ';
const qs=(s,r=document)=>r.querySelector(s),qsa=(s,r=document)=>[...r.querySelectorAll(s)];
const menuData=[
['Matcha','MATCHA DÂU DỪA','Matcha Coconut Strawberry',85],['Matcha','MATCHA KHOAI LANG TÍM','Ube Matcha',85],['Matcha','MATCHA DƯA HẤU','Watermelon Matcha',85],['Matcha','MATCHA CHUỐI','Banana Matcha',79],['Matcha','MATCHA TRÀ BÁ TƯỚC','Earl Grey Matcha',85],['Matcha','MATCHA SỮA','Latte / Cold-whisked Matcha',75],['Matcha','MATCHA TRUYỀN THỐNG','Usucha',75],['Matcha','MATCHA BỒNG BỀNH','Cloudy Matcha',85],['Matcha','MATCHA PUDDING CHUỐI','Banana Pudding Matcha',85],
['Houjicha','HOUJICHA CHUỐI','Banana Houjicha',65],['Houjicha','HOUJICHA SỮA','Cold-whisked Houjicha',59],['Houjicha','HOUJICHA TRÀ BÁ TƯỚC','Earl Grey Houjicha',69],['Houjicha','HOUJICHA PUDDING CHUỐI','Banana Pudding Houjicha',69],
['Tea & Cacao','TRÀ DÂU ỔI BASIL','Straw-ava Basil Iced Tea',69],['Tea & Cacao','TRÀ ĐÀO THANH YÊN','Yuzu Peach Iced Tea',65],['Tea & Cacao','CHOCOLATE NÓNG/LẠNH','Classic Chocolate',59],
['Coffee','CÀ PHÊ 0°C','Kori Kohi',55],['Coffee','CÀ PHÊ THANH YÊN','Yuzu Espresso',65],['Coffee','CÀ PHÊ ĐEN','Vietnamese Black Coffee',49],['Coffee','CÀ PHÊ SỮA','Vietnamese Milk Coffee',52],['Coffee','BẠC XỈU','Vietnamese White Coffee',52],['Coffee','CÀ PHÊ SỮA TƯƠI','Coffee Latte',52],['Coffee','CÀ PHÊ MẬT ONG','Honey Latte',65],['Coffee','AMERICANO','Americano',55],
['Pastries','BÁNH KẸP NƯỚNG KEM','Snowball Croffle',55],['Pastries','BÁNH BÔNG LAN MỀM','Softy Sponge Cake',39],['Pastries','KEM LẠNH CÁC LOẠI','Assorted Ice Cream',29],['Pastries','PUDDING DÂU','Strawberry Pudding',25],['Pastries','PUDDING CHUỐI','Banana Pudding',25],
['Combo','BỘ BA HỢP CA','3 drinks, one from each section',185],['Combo','ĂN BÁNH UỐNG CÀ PHÊ','Coffee + Croffle',99],['Combo','ĂN BÁNH UỐNG TRÀ','Tea/Houjicha + Croffle',109],['Combo','ĂN BÁNH UỐNG MATCHA','Matcha + Croffle',119],
['Extras','CÀ PHÊ ESPRESSO','Coffee shot',8],['Extras','CÀ PHÊ VIÊN','Coffee cubes',8],['Extras','KEM BỒNG BỀNH','Creamy cloud',10],['Extras','KEM DÂU','Strawberry cloud',13],['Extras','KEM KHOAI LANG TÍM','Ube cloud',13],['Extras','KEM TRÀ BÁ TƯỚC','Earl Grey cloud',13],['Extras','PUDDING DÂU','Strawberry pudding',15],['Extras','PUDDING CHUỐI','Banana pudding',15],['Extras','OATSIDE','Plant milk',5],['Extras','OATLY','Plant milk',8]
];
const productImages={'AMERICANO':'/assets/coffee-americano.webp','BẠC XỈU':'/assets/coffee-bacxiu.webp'};
let cart=JSON.parse(localStorage.getItem('tilly_cart')||'[]');
let currentProduct=null,currentOptions={sweet:'100%',ice:'100%',milk:'Regular',qty:1};
function updateCount(){qsa('[data-cart-count]').forEach(el=>el.textContent=cart.reduce((s,x)=>s+x.qty,0))}
function saveCart(){localStorage.setItem('tilly_cart',JSON.stringify(cart));updateCount();renderCart()}
function toggleMobile(){qs('.mobile-panel')?.classList.toggle('open')}
function openCart(){renderCart();qs('#cartOverlay')?.classList.add('show');qs('#cartDrawer')?.classList.add('show')}
function closeLayers(){qs('#cartOverlay')?.classList.remove('show');qs('#cartDrawer')?.classList.remove('show');qs('#productModal')?.classList.remove('show')}
function renderCart(){const list=qs('#cartList'),total=qs('#cartTotal');if(!list||!total)return;list.innerHTML=cart.length?cart.map((x,i)=>`<div class="cart-row"><b>${x.name}</b><small>${x.options||''}</small><div>${x.qty} × ${fmt(x.unit)} <button class="icon-btn" type="button" aria-label="Remove ${x.name}" onclick="removeCart(${i})">×</button></div></div>`).join(''):'<p class="muted">Your cart is empty.</p>';total.textContent=fmt(cart.reduce((s,x)=>s+x.qty*x.unit,0))}
function removeCart(i){cart.splice(i,1);saveCart()}
function showProduct(i){currentProduct=menuData[i];currentOptions={sweet:'100%',ice:'100%',milk:'Regular',qty:1};qs('#modalCat').textContent=currentProduct[0];qs('#modalName').textContent=currentProduct[1];qs('#modalEn').textContent=currentProduct[2];const im=qs('#modalImage');if(im){const src=productImages[currentProduct[1]];im.hidden=!src;if(src){im.src=src;im.alt=currentProduct[1]+' at Tilly House'}}renderOptions();qs('#cartOverlay')?.classList.add('show');qs('#productModal')?.classList.add('show')}
function renderOptions(){if(!currentProduct)return;const drink=!['Pastries','Combo','Extras'].includes(currentProduct[0]);const target=qs('#optionArea');if(!target)return;target.innerHTML=drink?optionGroup('Sweetness',['50%','100%','150%'],'sweet')+optionGroup('Ice',['50%','100%','150%'],'ice')+optionGroup('Plant milk',['Regular','Oatside +5K','Oatly +8K'],'milk'):'<p class="muted">No drink customization required for this item.</p>';qs('#modalQty').textContent=currentOptions.qty;qs('#modalTotal').textContent=fmt((currentProduct[3]+milkExtra())*currentOptions.qty)}
function optionGroup(title,values,key){return `<div class="option-title">${title}</div><div class="option-list">${values.map(v=>`<button type="button" class="option ${currentOptions[key]===v?'active':''}" onclick="setOption('${key}','${v}')">${v}</button>`).join('')}</div>`}
function setOption(k,v){currentOptions[k]=v;renderOptions()}
function changeQty(d){currentOptions.qty=Math.max(1,currentOptions.qty+d);renderOptions()}
function milkExtra(){return currentOptions.milk==='Oatside +5K'?5:currentOptions.milk==='Oatly +8K'?8:0}
function addCurrent(){if(!currentProduct)return;const drink=!['Pastries','Combo','Extras'].includes(currentProduct[0]);const opts=drink?`${currentOptions.sweet} sweet · ${currentOptions.ice} ice · ${currentOptions.milk}`:'';cart.push({name:currentProduct[1],qty:currentOptions.qty,unit:currentProduct[3]+milkExtra(),options:opts});saveCart();closeLayers();openCart()}
function renderMenu(cat='Matcha'){const grid=qs('#menuGrid'),cats=qs('#menuCats');if(!grid||!cats)return;const categories=[...new Set(menuData.map(x=>x[0]))];cats.innerHTML=categories.map(c=>`<button type="button" class="${c===cat?'active':''}" onclick="renderMenu('${c.replaceAll("'","\\'")}')">${c}</button>`).join('');grid.innerHTML=menuData.map((x,i)=>({x,i})).filter(o=>o.x[0]===cat).map(o=>{const img=productImages[o.x[1]];const body=`<div class="menu-item-body"><div class="eyebrow">${o.x[0]}</div><h3>${o.x[1]}</h3><div class="en">${o.x[2]}</div><div class="menu-item-foot"><b>${fmt(o.x[3])}</b><button type="button" class="round-add" aria-label="Customize and add ${o.x[1]}" onclick="showProduct(${o.i})">+</button></div></div>`;return `<article class="menu-item${img?' has-image':''}">${img?`<img class="menu-thumb" src="${img}" alt="${o.x[2]} at Tilly House" loading="lazy">`:''}${body}</article>`}).join('')}
function sendOrder(){if(!cart.length)return alert('Cart đang trống.');const name=qs('#orderName')?.value.trim()||'',phone=qs('#orderPhone')?.value.trim()||'',where=qs('#orderWhere')?.value||'Café / Pick-up';if(!name||!phone)return alert('Vui lòng nhập tên và số điện thoại.');const lines=cart.map(x=>`${x.qty}x ${x.name} — ${fmt(x.unit*x.qty)}${x.options?' — '+x.options:''}`);const text=`TILLY HOUSE ORDER\n${lines.join('\n')}\n\nTotal: ${fmt(cart.reduce((s,x)=>s+x.unit*x.qty,0))}\nName: ${name}\nPhone: ${phone}\nLocation: ${where}`;window.open('https://wa.me/84888498679?text='+encodeURIComponent(text),'_blank')}
const roomPrices={AOARASHI:{'2H':350,'8H':990,'1N':1350},CHITOSE:{'2H':450,'8H':1450,'1N':1890}};
function updateBooking(){const r=qs('#bookRoom'),d=qs('#bookDuration'),out=qs('#bookingSummary');if(!r||!d||!out)return;const label=d.value==='1N'?'1 Night':d.value.replace('H',' Hours');out.innerHTML=`<span class="secure-mark">Selected stay</span><br><b>${r.value} · ${label}</b><br>${fmt(roomPrices[r.value][d.value])}`}
function homeBooking(){const room=qs('#quickRoom')?.value||'AOARASHI',duration=qs('#quickDuration')?.value||'2H',date=qs('#quickDate')?.value||'',time=qs('#quickTime')?.value||'14:00';const p=new URLSearchParams({room,duration});if(date)p.set('date',date);if(time)p.set('time',time);location.href='/booking?'+p.toString()}
function prefillBooking(){const p=new URLSearchParams(location.search),map={room:'#bookRoom',duration:'#bookDuration',date:'#bookDate',time:'#bookTime'};Object.entries(map).forEach(([k,s])=>{const el=qs(s),v=p.get(k);if(el&&v)el.value=v});const min=new Date();min.setMinutes(min.getMinutes()-min.getTimezoneOffset());qsa('input[type="date"]').forEach(el=>{el.min=min.toISOString().slice(0,10)});updateBooking()}
function sendBooking(){const r=qs('#bookRoom'),d=qs('#bookDuration'),date=qs('#bookDate'),time=qs('#bookTime'),name=qs('#bookName'),phone=qs('#bookPhone'),email=qs('#bookEmail'),note=qs('#bookNote'),payment=qs('input[name="payment_method"]:checked');if(!date?.value||!name?.value.trim()||!phone?.value.trim())return alert('Vui lòng nhập ngày, tên và số điện thoại.');const label=d.value==='1N'?'1 Night':d.value.replace('H',' Hours');const method=payment?.value||'PayPal / Card after confirmation';const text=`TILLY HOUSE BOOKING REQUEST\nRoom: ${r.value}\nStay: ${label}\nDate: ${date.value}\nTime: ${time?.value||''}\nPrice: ${fmt(roomPrices[r.value][d.value])}\nPreferred payment: ${method}\nName: ${name.value}\nPhone: ${phone.value}\nEmail: ${email?.value||''}\nNote: ${note?.value||''}`;window.open('https://wa.me/84888498679?text='+encodeURIComponent(text),'_blank')}
document.addEventListener('DOMContentLoaded',()=>{updateCount();renderCart();if(qs('#menuGrid'))renderMenu('Matcha');if(qs('#bookingSummary'))prefillBooking();const qd=qs('#quickDate');if(qd){const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());qd.min=d.toISOString().slice(0,10)}});
window.toggleMobile=toggleMobile;window.openCart=openCart;window.closeLayers=closeLayers;window.removeCart=removeCart;window.showProduct=showProduct;window.setOption=setOption;window.changeQty=changeQty;window.addCurrent=addCurrent;window.renderMenu=renderMenu;window.sendOrder=sendOrder;window.updateBooking=updateBooking;window.sendBooking=sendBooking;window.homeBooking=homeBooking;
